project:
  type: website
  output-dir: docs

website:
  title: "Katherine T. McCabe"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual
