---
title: "Research"
format: html
editor: visual
---

My current research and published work span American politics and political behavior, with a focus on political psychology and communication, public opinion, and policy feedback. I am particularly interested in how people resolve tension between their political orientations and their social identities and personal experiences when engaging in politics. 

**Current Projects**

[*Engaging Imperfect Partisans.*]{.underline}Partisanship has a tremendous influence on political preferences and behavior in American politics. However, people are not perfect partisans. Most partisans disagree with their party on at least one issue or have a social identity that is more typically associated with the opposing party. In this project, I study how these conflicts influence political behavior, and potential interventions to help reduce the often aversive nature of political experiences for these individuals to help broaden political participation.

[*Public Opinion on Health Care*]{.underline}*.* A majority of U.S. adults have had an unexpected health event or report that they have at some point experienced a medical bill they could not afford. In a series of papers, I examine how personal experiences with health care costs and other negative health care experiences influence the attitudes individuals hold toward health reform policy and government involvement in the health care system.

**Peer-Reviewed Publications**

McCabe, Katherine T. 2023. "Explaining Variation in Support for Government Action on Unexpected 
Medical Bills." Journal of Health Policy, Politics and Law 48(3):405-434 https://doi.og/10.1215/03616878-10358738 

McCabe, Katherine T. 2023. "Spreading the Blame: Personal Experience and Attribution for Health 
Care Expenses." Journal of Elections, Public Opinion & Parties 33(3), 365-376. https://doi.org/10.1080/17457289.2022.2113089

McCabe, Katherine. 2023. "Engaging Multiple Identity Frames in Political Discussion." Politics, Groups, 
and Identities 11(5), 1138-1157. https://doi.org/10.1080/21565503.2022.2086473

McCabe, Katherine T. 2022. "Can We Learn from 2012? Priming and Abortion's Influence on Voting 
Decisions." Electoral Studies 79, 102518. https://doi.org/10.1016/j.electstud.2022.102518

Chen, Amanda and Katherine T. McCabe. 2022. "Roses and Thorns: Political Talk in Reality TV 
Subreddits" New Media and Society 1-23. https://doi.org/10.1177%2F14614448221099180.

Kolcak, Burcu and Katherine T. McCabe. 2022. "Public Opinion, Federalism, and Level of 
Governmental Intervention: Perceptions of Law Enforcement Response to the 2020 George 
Floyd Protests." Publius: The Journal of Federalism https://doi.org/10.1093/publius/pjac009.

Asbury-Kimmel, Victoria, Keng-Chi Chang, Katherine McCabe, Kevin Munger, and Tiago Ventura. 
2021. "The Effect of Streaming Chat on Perceptions of Debates." Journal of Communication 
71:947-975, jqab041, https://doi.org/10.1093/joc/jqab041

Kolcak, Burcu and Katherine T. McCabe. 2021. "Federalism at a partisan's convenience: public opinion 
on federal intervention in 2020 election policy." Journal of Elections, Public Opinion and Parties, 
31(sup1), 167-179. https://doi.org/10.1080/17457289.2021.1924741 

Ventura, Tiago, Munger, Kevin, McCabe, Katherine T., and Chang, Keng-Chi. 2021. "Connective 
Effervescence and Streaming Chat During Political Debates." Journal of Quantitative Description: 
Digital Media, 1. https://doi.org/10.51685/jqd.2021.001 

Walker, Hannah L., Katherine T. McCabe & Yalidy Matos. 2021. "Proximal contact with Latino 
immigrants and immigration attitudes." Politics, Groups, and Identities.  https://doi.org/10.1080/21565503.2021.1882315 

Funck, Amy S. and Katherine T. McCabe. 2021. "Partisanship, Information, and the Conditional Effects 
of Scandal on Voting Decisions." Political Behavior. 
https://doi.org/10.1007/s11109-020-09670-x 

McCabe, Katherine, Yalidy Matos, and Hannah Walker. 2021. "Priming Legality: Perceptions of Latino 
and Undocumented Latino Immigrants." American Politics Research 49(1): 106-113. https://doi.org/10.1177/1532673X20959600. 

Feick, Lukas, Karsten Donnay, and Katherine T. McCabe. 2021. "The Subconscious Effect of Subtle 
Media Bias on Perceptions of Terrorism." American Politics Research 49(3): 313-318. 
https://doi.org/10.1177/1532673X20972105. 

McCabe, Katherine T. 2021. "Variation in Perceptions of Sexual Identity: Partisanship and Personal 
Exposure." Politics, Groups, and Identities 9(5): 955-974.  https://doi.org/10.1080/21565503.2019.1674673.  

McCabe, Katherine T. 2019. "The Persistence of Racialized Health Care Attitudes: Racial Attitudes 
among White Adults and Identity Importance among Black Adults. The Journal of Race, 
Ethnicity, and Politics, 4(2), 378-98. https://doi.org/10.1017/rep.2019.20. 

McCabe, Katherine T. 2019. "Person-Positivity Bias, Social Category Labels, and Attitudes toward 
Gays and Lesbians." Research & Politics. https://doi.org/10.1177/2053168019858850. 

Lerman, Amy E. and Katherine T. McCabe. 2017. "Personal Experience and Public Opinion: Assessing 
Conditional Policy Feedback." The Journal of Politics 79(2): 624-41. https://doi.org/10.1086/689286

Mendelberg, Tali, Katherine T. McCabe, and Adam Thal. 2017. "College Socialization and the 
Economic Views of Affluent Americans." American Journal of Political Science 61(3): 606-23. 
https://doi.org/10.1111/ajps.12265   

McCabe, Katherine T. 2016. "Attitude Responsiveness and Partisan Bias: Direct Experience with the 
Affordable Care Act." 2016. Political Behavior 38(4): 861-82.
 https://doi.org/10.1007/s11109-016-9337-9. 

Lerman, Amy E., Katherine T. McCabe, and Meredith L  Sadin. 2015. "Political Ideology, Skin Tone, 
and the Psychology of Candidate Evaluations." Public Opinion Quarterly 79(1): 53-90. 
https://doi.org/10.1093/poq/nfu055 

Hopkins, Daniel J. and Katherine T. McCabe. 2012. "After It's Too Late: Estimating the Policy Impacts 
of Black Mayoralties in U.S. Cities." American Politics Research 40(4): 665-700. 
https://doi.org/10.1177/1532673X11432469. 

**Book Chapter**

Matos, Yalidy and Katherine McCabe. 2022. "America's Lack of Political Beliefs and the Consequences for Democracy." In J. Musolino, J. Sommer, and P. Hemmer (Eds.), The Cognitive Science of Belief. Cambridge, MA: Cambridge University Press, pp. 298-320. https://doi.org/10.1017/9781009001021.022 

